import os
import psycopg2
import psycopg2.extras
from prettytable import PrettyTable
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    """
    Execute the EMF query and return results as a PrettyTable.
    """
    load_dotenv()

    user = os.getenv('USERNAMEZ')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor, host='127.0.0.1', port='5432')
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    class MFStruct:
        def __init__(self):
            self.cust = ''
            self.count_1_quant = 0
            self.sum_2_quant = 0
            self.max_3_quant = float('-inf')

    # For entries in the H-Table    
    data = []
    # To ensure distinct records based on grouping-attributes   
    group_by_map = {}

    # First scan: Create entries for distinct grouping attribute values
    for row in cur:
        key = (row.get('cust'))
        
        if key not in group_by_map:
            entry = MFStruct()
            entry.cust = row.get('cust')
            data.append(entry)
            group_by_map[key] = len(data) - 1


if __name__ == "__main__":
    print(query())
