import os
import psycopg2
import psycopg2.extras
from prettytable import PrettyTable
from dotenv import load_dotenv
from tabulate import tabulate

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    """
    Execute the EMF query and return results as a PrettyTable.
    """
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor, host='127.0.0.1', port='5432')
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    class MFStruct:
        def __init__(self):
            self.prod = ''
            self.sum_1_quant = 0
            self.sum_2_quant = 0

    # For entries in the H-Table    
    data = []
    # To ensure distinct records based on grouping-attributes   
    group_by_map = {}

    # First scan: Create entries for distinct grouping attribute values
    for row in cur:
        key = (row.get('prod'))
        
        if key not in group_by_map:
            entry = MFStruct()
            entry.prod = row.get('prod')
            data.append(entry)
            group_by_map[key] = len(data) - 1

    # Scan for grouping variable 1
    cur.scroll(0, mode='absolute')

    for row in cur:
        for pos in range(len(data)):
            prod = data[pos].prod
            if row.get('state') == 'NY' and row.get('prod') == prod:
                data[pos].sum_1_quant += row.get('quant')

    # Scan for grouping variable 2
    cur.scroll(0, mode='absolute')

    for row in cur:
        for pos in range(len(data)):
            prod = data[pos].prod
            if row.get('prod') == prod:
                data[pos].sum_2_quant += row.get('quant')

    if not os.path.exists('outputs'):
        os.makedirs('outputs')

    headers = ['prod', 'sum_1_quant', 'sum_2_quant', 'sum_1_quant / sum_2_quant']
    table_rows = []
    for obj in data:
        row_vals = []
        for field in ['prod', 'sum_1_quant', 'sum_2_quant', 'sum_1_quant / sum_2_quant']:
            try:
                val = getattr(obj, field)
            except AttributeError:
                try:
                    val = eval(field, {}, obj.__dict__)
                except Exception:
                    val = ''
            row_vals.append(str(val))
        table_rows.append(row_vals)

    output_path = os.path.join('outputs', 'phi_6.txt')
    with open(output_path, 'w') as f:
        f.write(tabulate(table_rows, headers=headers, tablefmt='psql'))

    return len(data)

if __name__ == "__main__":
    print(query())
